// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteAPI.Data;

#nullable disable

namespace RestauranteAPI.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    [Migration("20250517150638_CriacaotabelaBalanco")]
    partial class CriacaotabelaBalanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RestauranteAPI.Data.Models.Balanco", b =>
                {
                    b.Property<int>("IdBalanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBalanco"));

                    b.Property<int>("IdPrato")
                        .HasColumnType("int");

                    b.Property<int>("TipoBalanco")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdBalanco");

                    b.HasIndex("IdPrato");

                    b.ToTable("Balanco");
                });

            modelBuilder.Entity("RestauranteAPI.Data.Models.CategoriaPrato", b =>
                {
                    b.Property<int>("IdCategoriaPrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoriaPrato"));

                    b.Property<string>("DescricaoCategoria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdCategoriaPrato");

                    b.ToTable("Categoria_Prato");
                });

            modelBuilder.Entity("RestauranteAPI.Data.Models.Prato", b =>
                {
                    b.Property<int>("IdPrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPrato"));

                    b.Property<string>("DescricaoPrato")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdCategoriaPrato")
                        .HasColumnType("int");

                    b.Property<string>("NomePrato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValorPrato")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdPrato");

                    b.HasIndex("IdCategoriaPrato");

                    b.ToTable("Prato");
                });

            modelBuilder.Entity("RestauranteAPI.Data.Models.Balanco", b =>
                {
                    b.HasOne("RestauranteAPI.Data.Models.Prato", "Prato")
                        .WithMany("Balanco")
                        .HasForeignKey("IdPrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("RestauranteAPI.Data.Models.Prato", b =>
                {
                    b.HasOne("RestauranteAPI.Data.Models.CategoriaPrato", "CategoriaPrato")
                        .WithMany("Pratos")
                        .HasForeignKey("IdCategoriaPrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPrato");
                });

            modelBuilder.Entity("RestauranteAPI.Data.Models.CategoriaPrato", b =>
                {
                    b.Navigation("Pratos");
                });

            modelBuilder.Entity("RestauranteAPI.Data.Models.Prato", b =>
                {
                    b.Navigation("Balanco");
                });
#pragma warning restore 612, 618
        }
    }
}
